export const SWITCH_VIEW = 'SWITCH_VIEW';
export const SORT_COLUMN = "SORT_COLUMN";
export const VISIBLE_PARTERRE = 'VISIBLE_PARTERRE';
export const VISIBLE_FIRST_FLOOR = 'VISIBLE_FIRST_FLOOR';
export const VISIBLE_GARDEN = 'VISIBLE_GARDEN';
export const VISIBLE_LOFT = 'VISIBLE_LOFT';
export const CHANGE_FLOOR = 'CHANGE_FLOOR';

