export const SWITCH_VIEW = 'SWITCH_VIEW';
export const SORT_COLUMN_MAX_MIN = "SORT_COLUMN_MAX_MIN";
export const SORT_COLUMN_MIN_MAX = "SORT_COLUMN_MIN_MAX";
export const CHANGE_FLOOR = 'CHANGE_FLOOR';
export const CHANGE_GARDEN = 'CHANGE_GARDEN';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const CHANGE_PRICE = 'CHANGE_PRICE';